### ISSUE TITLE
final project

### ISSUE THREAD

**Issue by kevenma** [kevenma/Final-Project#1]
So I have 2 ideas right now , its to either make a first person shooter game , or a app that send you recipes  with the ingredients you have in your fridge

 @amcooper @zhenpanda @williamfshaw @jasonseminara

**Comment by jasonseminara** [comment]
I think the recipe app is the most attainable and straightforward. Please write out a proper proposal including user stories and use cases so that I can properly evaluate it.

**Comment by kevenma** [comment]
Fridge App - Put in ingredients you have in your fridge and get back a recipe you can make for a delicious meal. 

User stories 

User can enter ingredients and get back recipes.
User can favorite recipes
User can click on the recipes and it will show the recipe and the nutrition and calories

@jasonseminara
